import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { supabaseAdmin } from "@/lib/supabase";

/**
 * Kitchen display auth has two modes:
 *
 * 1. Session (dashboard kitchen page — staff/owner logged in):
 *    Standard next-auth session; restaurant_id taken from the JWT.
 *
 * 2. Dedicated kitchen screen (wall-mounted tablet, not logged in):
 *    Must supply ?slug=<slug>&token=<kitchen_token> for GET, or
 *    { slug, token } in the PUT body.
 *    kitchen_token is a per-restaurant secret generated by migration 024.
 *    It is NOT the same as the public ordering slug.
 *
 * [P0 FIX] The old code accepted slug alone as auth, which is equivalent to
 * no auth — slugs are public (they appear in customer ordering URLs).
 */

// GET /api/kitchen?slug=xxx&token=xxx — fetch active orders for kitchen display
export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url);
  const slug = searchParams.get("slug");
  const token = searchParams.get("token");

  let restaurantId: string | null = null;

  // Auth method 1: Session (dashboard kitchen page)
  const session = await getServerSession(authOptions);
  if (session) {
    restaurantId = (session.user as any).restaurant_id;
  }

  // Auth method 2: Slug + kitchen_token (dedicated kitchen screen)
  // Both slug AND token must be present; token must match the stored value.
  if (!restaurantId && slug && token) {
    const { data: restaurant } = await supabaseAdmin
      .from("restaurants")
      .select("id, kitchen_token")
      .eq("slug", slug)
      .eq("is_active", true)
      .single();

    if (restaurant && restaurant.kitchen_token === token) {
      restaurantId = restaurant.id;
    }
  }

  if (!restaurantId) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  // Fetch active orders (confirmed, preparing, ready, out_for_delivery)
  const { data, error } = await supabaseAdmin
    .from("orders")
    .select("id, order_number, status, order_type, customer_name, customer_phone, delivery_address, items, notes, total, created_at")
    .eq("restaurant_id", restaurantId)
    .in("status", ["confirmed", "preparing", "ready", "out_for_delivery"])
    .order("created_at", { ascending: true });

  if (error) return NextResponse.json({ error: error.message }, { status: 500 });
  return NextResponse.json(data || []);
}

// PUT /api/kitchen — update order status from kitchen display
export async function PUT(req: NextRequest) {
  const body = await req.json();
  const { order_id, status, slug, token } = body;

  if (!order_id || !status) {
    return NextResponse.json({ error: "Order ID and status required" }, { status: 400 });
  }

  let restaurantId: string | null = null;

  const session = await getServerSession(authOptions);
  if (session) {
    restaurantId = (session.user as any).restaurant_id;
  }

  if (!restaurantId && slug && token) {
    const { data: restaurant } = await supabaseAdmin
      .from("restaurants")
      .select("id, kitchen_token")
      .eq("slug", slug)
      .eq("is_active", true)
      .single();
    if (restaurant && restaurant.kitchen_token === token) restaurantId = restaurant.id;
  }

  if (!restaurantId) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const validStatuses = [
    "confirmed", "preparing", "ready", "out_for_delivery",
    "delivered", "collected",
  ];
  if (!validStatuses.includes(status)) {
    return NextResponse.json({ error: "Invalid status" }, { status: 400 });
  }

  const { error } = await supabaseAdmin
    .from("orders")
    .update({ status })
    .eq("id", order_id)
    .eq("restaurant_id", restaurantId);

  if (error) return NextResponse.json({ error: error.message }, { status: 500 });

  // Log status history
  await supabaseAdmin.from("order_status_history").insert({
    order_id,
    status,
    changed_by: session ? (session.user as any).id : null,
  });

  return NextResponse.json({ success: true });
}
